---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    require_chef_omnibus: true
    memory: 1024

suites:
- name: default
  run_list:
    - role[skyline-cf]
  attributes:
